"""Extract a short decision brief from recorded PDFs that are still open."""

import fitz
from pathlib import Path

FILES = [
    "An Interactional Account of Empathy in Human-Machine Communicatio.pdf",
    "Artificial Sociality.pdf",
    "explain. write. edit. summarise_ An Exploratory Study on Agency N.pdf",
    "I Get by With a Little Help From My Bots_ Implications of Machine.pdf",
    "Triggered by Socialbots_ Communicative Anthropomorphization of Bo.pdf",
    "Chatbot vs. Human_ The Impact of Responsive Conversational Featur.pdf",
    "Communication Style Adaptation in Human-Computer Interaction_ An.pdf",
    "Prompted by Me. Generated by ChatGPT.pdf",
    "CASA Renovations_ Examining Social Responses to an Anthropomorphi.pdf",
    "Tools or Teammates_ Examining Agency Negotiation in Human-GenAI C.pdf",
    "10 Questions to Fall in Love with A Chatbot_ An Experimental Stud.pdf",
    "Gender and Task Alignment Influences the Credibility of Feminine.pdf",
    "Tool or Social Actor_ How AI Perception and Interaction Modality.pdf",
    "Beyond Human Bonds_ Understanding Relationship Development with H.pdf",
    "The Right Kind of Human-Like_ Measuring and Testing Human-Likenes.pdf",
    "3715275.3732045.pdf",
    "3805689.3812324.pdf",
    "00132-Full.AkbulutC.pdf",
    "00033-Student.MaedaT.pdf",
    "00422-MainTrack.MaedaT.pdf",
    "3786304.3787880.pdf",
    "3773077.3813785.pdf",
    "1-s2.0-S2949882126000472-main.pdf",
    "s10676-026-09917-x.pdf",
    "eejpl_13_1_2026_Mugableh_etal.pdf",
    "preprint-99710-submitted.pdf",
    "preprint-108858-submitted.pdf",
    "The_Anthropomorphic_Trap.pdf",
    "The pronoun is the policy_FC Spisländer (2026).pdf",
    "A Descriptive Index of Constraint-Induced Linguistic Patterning in Large Language Models.pdf",
    "Demystifying Apparent Experience in Large Language Models.pdf",
    "Empathic Mimicry in Conversational Artificial Intelligence.pdf",
    "Ema Drift Casebook.pdf",
    "OSED-Ko_Open-Source_Empathy-Driven_Dialogue_Dataset_for_Emotional_Support_of_Marginalized_Populations_in_South_Korea.pdf",
    "2607.13924v2.pdf",
    "10.1515_lass-2026-0021.pdf",
    "120232.pdf",
    "Simulated_Selfhood_in_LLMs__Preprint_Version.pdf",
    "ssrn-4974107.pdf",
    "ssrn-5404666.pdf",
    "ssrn-5431338.pdf",
    "ssrn-5813342.pdf",
    "techrxiv.175000893.36094030_v1.pdf",
    "metaphor_stabilization_ai_v0_3_.pdf",
    "WorkingPaper_Hallucinations_IA_Grangeret.pdf",
    "Paper 5 Non Anthropomorphic Identity .pdf",
    "AVA - Ambiguity_Vital_Area.pdf",
    "3630106.3658956.pdf",
    "Whats_It_Like_to_Trust_an_LLM_The_Devolution_of_Trust_Psychology.pdf",
]

ROOT = Path(__file__).resolve().parents[1] / "data" / "fulltext" / "recorded"
OUT = Path(__file__).resolve().parents[1] / "data" / "fulltext" / "oa_attempts" / "recorded_briefs.txt"
KEYS = ("abstract", "chatgpt", "large language", "llm", "pronoun", "polite", "empath", "first-person", "first person", "honorific", "anthropomorph")


def main():
    parts = []
    for name in FILES:
        path = ROOT / name
        if not path.exists():
            # filename encoding fallback
            hits = list(ROOT.glob(name[:24] + "*"))
            path = hits[0] if hits else None
        if path is None or not path.exists():
            parts.append(f"\n===== MISSING {name}\n")
            print("missing", name[:40])
            continue
        doc = fitz.open(path)
        text = "\n".join(page.get_text() for page in doc[:6])
        flat = " ".join(text.split())
        parts.append(f"\n===== {path.name} pages={doc.page_count}\n")
        parts.append(flat[:1600] + "\n")
        print("ok", path.name[:50], doc.page_count)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text("".join(parts), encoding="utf-8")
    print("wrote", OUT, "chars", OUT.stat().st_size)


if __name__ == "__main__":
    main()
